#ifndef _PINMUX_CONFIG_H
#define _PINMUX_CONFIG_H

/* Tang 4K production board:
 *   JTAG TDI/TDO/TMS/TCK -> GPIO0/1/2/15
 *   UART1 TX/RX          -> GPIO26/27
 *   active-low LED       -> GPIO17
 * GPIO2 must not be configured as UART0 TX on this board. */
#define CONFIG_GPIO0_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO1_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO2_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO7_FUNC  GPIO_FUN_USB
#define CONFIG_GPIO8_FUNC  GPIO_FUN_USB
#define CONFIG_GPIO9_FUNC  GPIO_FUN_UNUSED
#define CONFIG_GPIO15_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO17_FUNC GPIO_FUN_UNUSED
#define CONFIG_GPIO26_FUNC GPIO_FUN_UART1_TX
#define CONFIG_GPIO27_FUNC GPIO_FUN_UART1_RX
#define CONFIG_GPIO28_FUNC GPIO_FUN_UNUSED

#endif
